mainprefix = "x"     # Ideally, replace "x" across the whole repo with your mod's mainprefix, example "t" (without the "")
prefix = "kolmi"             # Ideally, replace "kolmi" across the whole repo with your mod's prefix, example "mod" (without the "") 

name = "kolmipilot's hand signal menu"

[properties]
author = "kolmipilot"
url = "https://github.com/kolmipilot/signals"

[files]
include = [
    "mod.cpp",      # These files are copied to the build directory by default
    "meta.cpp",     # They do not need to be added to your list
    "LICENSE",
    "/img/*.paa",
    "logo_ca.paa",
    "logo_co.paa",
    "*.bikey",
]
exclude = [
    "*.psd",        # By default this list is empty
    "*.md",
    "/.vscode/",
]

[version]
git_hash = 0 # Default: 8
